sonar.projectKey=front-client
sonar.sources=components, store
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.coverage.exclusions=components/__tests__/**/*, *.config.js, node_modules/**/*, store/index.js, store/profile/action.js, store/profile/index.js, store/profile/__tests__/*
